version: "3"

services:
  websocket-server:
    container_name: websocket-server
    build: 
      context: .
      dockerfile: Dockerfile
    image: websocket-server
    command: air
    ports:
      - "8080:8080"
    volumes:
      - .:/app

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "8443:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../front/dist:/var/www
      - ./nginx/static:/etc/nginx/static
      - ./nginx/keys:/etc/nginx/keys
    tty: true
    extra_hosts:
      - host.docker.internal:host-gateway